---
#
# Initial testing of Ansible automation on NXOS9000v in VIRL
# Demonstration of linear playbook for single host (n9k2) using CLI/SSH transport
#
# Author: Quinn Snyder, Systems Engineer | Enterprise Southwest .:|:.:|:. Cisco Systems
# Date: 2018-02-01
# Version: 0.1a
#
- name: Demonstration of automation of Nexus 9000v-2 running in VIRL using Ansible CLI transport
  hosts: n9k2
  connection: network
  gather_facts: no

  tasks:

    - name: Ensure the OSPF feature is enabled
      nxos_feature:
        feature: ospf
        state: enabled

    - name: Configure Loopback0
      nxos_interface:
        description: 'Configured by Ansible'
        interface: loopback 0
        admin_state: up

    - name: Configure IP address on Loopback0
      nxos_l3_interface:
        name: Loopback0
        state: present
        ipv4: 2.2.2.2/32

    - name: Configure IP address on Ethernet1/2
      nxos_l3_interface:
        name: Ethernet1/2
        state: present
        ipv4: 12.12.12.13/24

    - name: Enable the OSPF process on the switch
      nxos_ospf:
        ospf: 1
        state: present

    - name: Configure OSPF on Ethernet1/2
      nxos_interface_ospf:
        interface: Ethernet1/2
        ospf: 1
        area: 0
        cost: default

    - name: Configure OSPF on Loopback0
      nxos_interface_ospf:
        interface: Loopback0
        ospf: 1
        area: 0
        cost: default
