---
#
# Initial testing of Ansible automation on NXOS9000v in VIRL
# Demonstration of provisioning both NXOS9000v hosts using single playbook based on roles with conditional revert
#
# Author: Quinn Snyder, Systems Engineer | Enterprise Southwest .:|:.:|:. Cisco Systems
# Date: 2018-02-26
# Version: 0.1a
#
- name: Demonstration of automation of Nexus 9000v devices running in VIRL using Ansible
  hosts: all
  connection: local
  gather_facts: no

  roles:
    - provision

  tasks:

    - name: Revert if OSPF routes not found
      import_role:
        name: revert
      when: result|failed