---
#
# Initial testing of Ansible automation on NXOS9000v in VIRL
# Demonstration of Ansible v2.4.0.0 running locally against hosts in PHX2 lab
#
# Author: Quinn Snyder, Systems Engineer | Enterprise Southwest
# Date: 2018-02-01
# Version: 0.1a
#
- name: Demonstration of automation of Nexus 9000v devices running in VIRL using Ansible
  hosts: all
  connection: local
  gather_facts: no

  roles:
    - provision

  tasks:

    - name: Revert if OSPF routes not found
      import_role:
        name: revert
      when: result|failed